import WeekOfMaster from "../pages/Workforce/WeekOfMaster/WeekOfMaster";
 export const appName="";
//  export const appName="/klikfmdev"
export const PATH = {
  
  PAGE_NOT_FOUND: "*",
  DEFAULT: "/",
  DASHBOARD: `${appName}/dashboard`,
  LOGIN: `${appName}/login`,
  USERROLEMASTER: `${appName}/userrolemasterlist`,
  SKILLMASTER:`${appName}/skillmasterlist`,
  USERMASTER:`${appName}/usermasterlist`,
  USERROLE_RIGHT: `${appName}/roleandright`,
  USERSKILLMSATER: `${appName}/userskillmaster`,
  LOCATIONTYPE: `${appName}/locationtype`,
  ADDBUILDING: `${appName}/addfacilitysetup`,
  BUILDINGSETUP: `${appName}/facilitydetail`,
  ADDLOCATION: `${appName}/location`,
  LANGUAGECHANGE: `${appName}/languageChange`,
  MAKEMASTER: `${appName}/makemaster`,
  TASKMASTER: `${appName}/taskmasterlist`,
  MODELMASTER: `${appName}/modelmaster`,
  ASSETGROUPMASTER: `${appName}/assetgroupmaster`,
  SERVICEGROUPMASTER: `${appName}/servicegroupmaster`,
  ASSETTYPEMASTER: `${appName}/assettypemaster`,
  SERVICETYPEMASTER: `${appName}/servicetypemaster`,
  UOMMASTER: `${appName}/uommaster`,
  ASSETMASTER: `${appName}/assetmasterlist`,
  PARTMASTER: `${appName}/partmasterlist`,
  SEVERITYMASTER: `${appName}/severitylist`,
  WORKORDERTYPE: `${appName}/workordertypelist`,
  WORKORDERSTATUS: `${appName}/workorderstatuslist`,
  CURRENTSTATUSCONFIG: `${appName}/currentstatusconfig`,
  STOREMASTER: `${appName}/storesetuplist`,
  RACKMASTER: `${appName}/rackmasterlist`,
  WEEKOFMASTER: `${appName}/weekoffmasterlist`,
  ASSETMASTERCONFIGURATION: `${appName}/assetmasterconfiguration`,
  REQDESCRIPTIONMASTER: `${appName}/requestdescriptionlist`,
  WORKORDERMASTER: `${appName}/workorderlist`,
  SAVENUMBERRANGECONFIG: `${appName}/numberrangeconfig`,
  VENDORMASTER: `${appName}/vendoremasterlist`,
  SERVICEMASTER: `${appName}/servicemasterlist`,
  TEAMMASTER: `${appName}/teammasterlist`,
  EVENTMASTER: `${appName}/eventmasterlist`,
  ESCALATIONMATRIX: `${appName}/escalationmatrixlist`,
  PPMSCHEDULE: `${appName}/ppmSchedule`,
  MATERIALREQUEST: `${appName}/materialrequestlist`,
  ISSUEMATERIAL: `${appName}/issuemateriallist`,
  RETURNMATERIAL: `${appName}/returnmateriallist`,
  STORETOSTORE: `${appName}/storetostorelist`,
  SERVICEREQUEST: `${appName}/servicerequestlist`,
  INVENTORYMASTER: `${appName}/addinventory`,
  PPMSCHEDULEDETAILS: `${appName}/ppmscheduledetails`,
  ASSETSCHEDULEMASTER: `${appName}/assettaskschedulelist`,
  MATERIALREQUESTPROVISION: `${appName}/materialrequestapprovelist`,
  ANALYTICSPLATEFORMASSETLINK: `${appName}/linkananlyticsplatformlist`,
  ANANLYTICSFDD: `${appName}/ananlyticsfddlist`,
  REASONMASTER:`${appName}/reasonmasterlist`,
  RECTIFIEDCOMMENT:`${appName}/rectifiedcommentlist`,
  SHOWSERVICEREQEST:`${appName}/servicerequestlist?edit=`,
  ADD_PPMSCHEDULE:`${appName}/ppmSchedule?add=`,
  ADD_ISSUEMATERIAL:`${appName}/issuemateriallist?add=`,
  EDIT_WORKORDERMASTER:`${appName}/workorderlist?edit=`,
  EDIT_ESCALATIONMATRIX:`${appName}/escalationmatrixlist?edit=`,
  ADD_ESCALATIONMATRIX:`${appName}/escalationmatrixlist?add=`
};


